language: c
sudo: false
addons:
  apt:
    sources:
    - sourceline: 'ppa:dank/guile-2.2'
    packages:
    - expect
    - libncurses5-dev
    - libncursesw5-dev
    - guile-2.2
    - debhelper
    - dh-make
    - fakeroot
cache:
before_install:
install: true
before_script:
- export PREFIX=~/a; mkdir ~/a; export PATH=~/a/bin:$PATH
- t/0003.t 2>>/dev/null 1>>/dev/null
- . 225/0000.1 && . 225/0000.0 && 225/0001.0 && 225/0002.0 && 225/0002.0 install
- ls -lR ./ && pwd
script:
- sh ./t/0000-who-is-this
- prove t/000{3,4}.t
after_script:
before_cache:
after_success:
- echo "=== Success, this is teco ==="
- cp -R debian/ ${SOURCE}
- cd ${SOURCE} && fakeroot dh binary && cd ..
- ls -lh
- dpkg-deb -c teco*.deb
after_failure:
- echo "=== Enter the failure ==="
before_deploy:
- echo "=== Enter the deploy ==="
- git config --local user.name "Gunter Liszewski (ci)"
- git config --local user.email "gunter.liszewski@gmail.com"
- git tag "staging/v$( scripts/git-version-gen VERSION --prefix release\\/v )"
- . Fn/002_ && 002_ && packages-here && ls -lh
- mkdir -p ./out/ && cp -v teco*.deb ./out/ && cp -v packages-here* ./out/ && ls -lh ./out/
- cp -v teco*.xz ./out/ && ls -lh ./out/
deploy:
  provider: releases
  api_key:
    secure: HnvNBgZs6F/+5KDQwczSSed8XvwBPYxIB6hp616K4J1hJRnLrV4vxd5EyV8S4UFnPOp6Qvb7/kTV2QzDvbikwHKyCVS3sIaxYgvMoKuiTlP04xQIKnnBDWM1w0MlGeiTjsahNttJ2pZkUQqJbttIFuI/80A1TiUjgSW1AUubrBFb8N5xYg2iMNpCBE/PYwjSTt5I+ugDJCKVZf0+jVi3K2sPQ4dBaAudCAuJpGYtFDymQIuhYMA537MHMZLsBta6AUIb8tYZ2x/x8m2gO+4ytysw5YkItZaVIgXxqYTgXjrN/Otvlndg6DQedyAmLlPAhklr5bsya97GdKSJfFFxw6NpEsjWjB/yILqu6D5GZzSj/2nE/dV4fObyPSJBnJq/k0UCoGOql90svfDwK3wGxElbq6x1dGL4fqNCXq9j/tuVrUFzzOABGLbdm3LZH8lbb4DURg+5uoGto8AsM0SToyGFHJOCzEgHeLQ2bxcNTHFj31hqpCecDtIJhe8SOVFv37GmQ43ZHkW+fuBbJuaepeBCT8qEZRBj5cg9PPnicLWNtXzSxA1qe7OnheSpVkzPQICOcXL/r571c9GNoOgUB4agzrFgow+/zQiJCVwRgkJDl81nt8epdTm7waJvgu8lMcSYZ0pt+ssZpTFOBVUt4sV06fOgEFykmlWUXi34d94=
  file_glob: true
  skip_cleanup: true
  file: "./out/*"
  on:
    repo: glisze/teco
    branch: feature/0017/ci-lp-a105
after_deploy:
after_script:
