language: c
sudo: false
install: true
addons:
  apt:
    packages:
    - libncurses5-dev
    - libncursesw5-dev
script:
- ./t/0001-who-is-this
- pushd src && . Fn/002_ && 002_
- 00-makedep0
- 00-make-linux genclp
- ./genclp
- 00-make-linux clean
- 00-make-linux
- popd
