language: c
sudo: false
addons:
  apt:
    sources:
    - sourceline: 'ppa:dank/guile-2.2'
    - sourceline: 'ppa:glisze/ppa0'
    packages:
    - expect
    - libncurses5-dev
    - libncursesw5-dev
    - guile-2.2
    - teco
cache:
before_install:
install: true
before_script:
- guile --version
- 193/0004.t
- which tecoc && echo ok || echo not ok
- whereis tecoc && echo ok || echo not ok
- type tecoc && echo ok 3 || echo not ok 3
script:
- sh ./t/0000-who-is-this
- prove -v
after_script:
before_cache:
after_success:
- echo "=== Success, this is teco ==="
after_failure:
- echo "=== Enter the failure ==="
before_deploy:
- echo "=== Enter the deploy ==="
deploy:
after_deploy:
after_script:
