language: c
sudo: false
addons:
  apt:
    sources:
    packages:
    - expect
    - libncurses5-dev
    - libncursesw5-dev
cache:
before_install:
- sudo add-apt-repository -y ppa:dank/guile-2.2
- sudo apt-get update -y
- sudo apt-get install -y -V guile-2.2
- sudo apt-get install -y -V texinfo
install: true
before_script:
- export PREFIX=~/a; mkdir ~/a; export PATH=~/a/bin:$PATH
- . 225/0000.1 && . 225/0000.0 && 225/0001.0 && 225/0002.0 && 225/0002.0 install
- ls -lR ~/a
- guile --version
script:
- sh ./t/0000-who-is-this
- prove
after_script:
before_cache:
after_success:
- echo "=== Success, this is teco ==="
after_failure:
- echo "=== Enter the failure ==="
before_deploy:
- echo "=== Enter the deploy ==="
deploy:
after_deploy:
after_script:
