baksrc.obj bldstr.obj clenup.obj cmatch.obj docjr.obj  doeves.obj +
doflag.obj echoit.obj err.obj    exea.obj   exeats.obj exeb.obj   +
exebar.obj exebsl.obj exec.obj   execcc.obj execln.obj execom.obj +
execrt.obj execst.obj execta.obj exectc.obj exectd.obj execte.obj +
execti.obj exectl.obj exectn.obj execto.obj exectp.obj exectq.obj +
exectr.obj exects.obj exectt.obj exectu.obj exectv.obj exectw.obj +
exectx.obj execty.obj exectz.obj exed.obj   exedgt.obj exedot.obj +
exedqu.obj exee.obj   exeequ.obj exeesc.obj exeexc.obj exeey.obj  +
exef.obj   exefb.obj  exeg.obj   exegtr.obj exeh.obj   exei.obj   +
exeill.obj exej.obj   exek.obj   exel.obj   exelbr.obj exelst.obj +
exem.obj   exen.obj   exenul.obj exenyi.obj exeo.obj   exeopr.obj +
exep.obj   exeprc.obj exepw.obj  exeq.obj   exeqes.obj exer.obj   +
exerbr.obj exertp.obj exes.obj   exescl.obj exet.obj   exeu.obj   +
exeund.obj exeusc.obj exev.obj   exew.obj   exex.obj   exey.obj   +
exez.obj   findes.obj findqr.obj flowec.obj flowee.obj flowel.obj +
getara.obj getnma.obj inccbp.obj init.obj   insstr.obj isradx.obj +
ln2chr.obj makdbf.obj makrom.obj popmac.obj pshmac.obj pushex.obj +
rdline.obj rdpage.obj readcs.obj replac.obj search.obj singlp.obj +
skpcmd.obj srclop.obj sserch.obj tabort.obj typbuf.obj typest.obj +
uminus.obj wrpage.obj zfrsrc.obj zmsdos.obj
